# Generated by Django 4.2.6 on 2023-11-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['-balance']},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('BL', 'Blocked'), ('DI', 'Discharge')], default='AC', max_length=2),
        ),
    ]
