# Generated by Django 4.2.6 on 2023-11-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_alter_bankaccount_options_alter_bankaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='code',
            field=models.CharField(default='A7-0001', max_length=7),
        ),
    ]
