# Generated by Django 4.2.6 on 2023-11-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0004_remove_bankaccount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
