# Generated by Django 4.2.6 on 2023-11-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0010_alter_bankaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
