# Generated by Django 4.2.6 on 2023-11-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0011_alter_bankaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='code',
            field=models.CharField(default='A7-0000', editable=False, max_length=7),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
