# Generated by Django 4.2.6 on 2023-11-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0012_alter_bankaccount_code_alter_bankaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='code',
            field=models.CharField(editable=False, max_length=7),
        ),
    ]
