# Generated by Django 4.2.6 on 2023-11-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='code',
            field=models.CharField(default='A1-0001', max_length=7, unique=True),
        ),
    ]
