# Generated by Django 4.2.6 on 2023-11-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_bankaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='code',
            field=models.CharField(default='A1-{id:04d}', max_length=7, unique=True),
        ),
    ]
