# Generated by Django 4.2.6 on 2023-11-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_bankaccount_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='id',
            new_name='bank_account_id',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='code',
        ),
    ]
