# Generated by Django 4.2.6 on 2023-11-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_id_bankaccount_bank_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bank_account_id',
            new_name='id',
        ),
    ]
