# Generated by Django 4.2.6 on 2023-11-08 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_account', '0015_remove_bankaccount_b_id_bankaccount_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.TextField(max_length=10)),
                ('concept', models.TextField(blank=True, max_length=200)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kind', models.CharField(choices=[('OUT', 'Outgoing'), ('INC', 'Incoming')], default='OUT', max_length=3)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_account.bankaccount')),
            ],
        ),
    ]
