# Generated by Django 4.2.6 on 2023-11-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timeStamp']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='agent',
            field=models.CharField(max_length=7),
        ),
    ]
