# Generated by Django 4.2.6 on 2023-11-10 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0015_remove_bankaccount_b_id_bankaccount_id'),
        ('transaction', '0003_rename_agent_transaction_cac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac', to='bank_account.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(max_length=7),
        ),
    ]
