# Generated by Django 4.2.6 on 2024-01-22 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bank_account', '0015_remove_bankaccount_b_id_bankaccount_id'),
        ('transaction', '0011_alter_transaction_cac'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transactions',
                to='bank_account.bankaccount',
            ),
            preserve_default=False,
        ),
    ]
