# Generated by Django 4.2.7 on 2024-02-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('OUT', 'Outgoing'), ('INC', 'Incoming'), ('PAY', 'Payment')], default='OUT', max_length=3),
        ),
    ]
