# Generated by Django 4.2.7 on 2023-11-03 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.TextField(max_length=40)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('BL', 'Blocked'), ('DI', 'Discharge')], default=('AC', 'Active'), max_length=2)),
                ('pin', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
