# Generated by Django 4.2.6 on 2023-11-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='alias',
            field=models.CharField(max_length=40),
        ),
    ]
