# Generated by Django 4.2.6 on 2023-11-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='pin',
        ),
    ]
