# Generated by Django 4.2.6 on 2023-11-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bank_account', '0001_initial'),
        ('card', '0004_remove_card_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.AddField(
            model_name='card',
            name='bank_account',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cards',
                to='bank_account.bankaccount',
            ),
            preserve_default=False,
        ),
    ]
