# Generated by Django 4.2.7 on 2023-11-04 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
        ('card', '0004_remove_card_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank_account.bankaccount'),
        ),
    ]
