# Generated by Django 4.2.7 on 2023-11-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_card_bank_account'),
        ('card', '0005_remove_card_user_card_bank_account'),
    ]

    operations = [
    ]
