# Generated by Django 4.2.7 on 2023-11-04 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
        ('card', '0006_merge_20231104_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='bank_account.bankaccount'),
        ),
    ]
