# Generated by Django 4.2.6 on 2023-11-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_alter_card_status_alter_card_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-alias']},
        ),
        migrations.AddField(
            model_name='card',
            name='code',
            field=models.CharField(default='C7-0001', max_length=7),
        ),
    ]
