# Generated by Django 4.2.6 on 2023-11-06 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_alter_card_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['alias']},
        ),
    ]
