# Generated by Django 4.2.6 on 2023-11-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_card_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pin',
            field=models.CharField(editable=False, max_length=3),
        ),
    ]
