# Generated by Django 4.2.6 on 2023-11-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_alter_card_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='get_pin',
            field=models.CharField(default='PHV', editable=False, max_length=3),
            preserve_default=False,
        ),
    ]
