# Generated by Django 4.2.6 on 2023-11-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0021_remove_card_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='code',
            field=models.CharField(default=1, editable=False, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
