# Generated by Django 4.2.6 on 2023-11-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0026_alter_card_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='get_pin',
        ),
    ]
