# Generated by Django 4.2.6 on 2023-11-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0015_remove_bankaccount_b_id_bankaccount_id'),
        ('card', '0028_remove_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='bank_account.bankaccount'),
        ),
    ]
